name: Convert LaTeX to HTML

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out GitHub repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          ref: main  # Always checkout the main branch
          fetch-depth: 0  # Fetch the full history to avoid shallow clone issues

      # Step 2: Set up Git for GitHub authentication
      - name: Set up Git for GitHub
        run: |
          git config user.name "GitHub Action"
      
      #  Step 3: Install Pandoc
      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc 
      - name: Convert LaTeX to HTML
        run: pandoc cv.tex -o cv.html

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add cv.html || true
          git diff --cached --quiet || (git commit -m "Update HTML CV from LaTeX" && git push)
